apiVersion: apps/v1
kind: Deployment
metadata:
  name: estudiantestrabajo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: estudiantestrabajo-mysql
  template:
    metadata:
      labels:
        app: estudiantestrabajo-mysql
    spec:
      containers:
        - name: estudiantestrabajo
          image: ivangues/estudiantestrabajo:2.0.1
          ports:
            - containerPort: 9090
          env:
            - name: DB_HOST
              value: {{Values.env.DB_HOST}}
            - name: DB_NAME
              value: {{Values.env.DB_NAME}}
            - name: DB_USERNAME
              value: {{Values.env.DB_USER_PASS}}
            - name: DB_PASSWORD
              value: {{Values.env.DB_USER_PASS}}
          resources:
            requests:
              cpu: "300m"
              memory: "600Mi"
            limits:
              cpu: "600m"
              memory: "1200Mi"
          startupProbe:
            httpGet:
              path: /vida
              port: 9090
            failureThreshold: 30
            periodSeconds: 60
          livenessProbe:
            httpGet:
              path: /vida
              port: 9090
            initialDelaySeconds: 3
            timeoutSeconds: 3
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 5