apiVersion: apps/v1
kind: Deployment
metadata:
  name: estudiantestrabajo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: estudiantestrabajo-mysql
  template:
    metadata:
      labels:
        app: estudiantestrabajo-mysql
    spec:
      containers:
        - name: estudiantestrabajo
          image: ivangues/estudiantestrabajo:2.0.0
          ports:
            - containerPort: 9090
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_NAME
              value: estudiantes
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: root
          resources:
            requests:
              cpu: "600m"
              memory: "600Mi"
            limits:
              cpu: "800m"
              memory: "800Mi"
          startupProbe:
            httpGet:
              path: /vida
              port: 9090
            failureThreshold: 30
            periodSeconds: 60
          livenessProbe:
            httpGet:
              path: /vida
              port: 9090
            initialDelaySeconds: 3
            timeoutSeconds: 3
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 5