apiVersion: v1
kind: Service
metadata:
  name: estudiantestrabajo-svc
spec:
  selector:
    app: estudiantestrabajo-mysql
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 9090
      protocol: TCP