name: Continous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Instalando javita
        uses: actions/setup-java@v3
        with:
            distribution: 'temurin'
            java-version: '17'
      - name: Make Gradle script executable
        run: chmod +x ./gradlew
      - name: Compilando mi proyecto <3
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
      - name: Helm Install
        run: |
          helm upgrade --install 1.16.0 Chart.yaml
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
